{% set name = "pyogrio" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geopandas/pyogrio/releases/download/v{{ version }}/pyogrio-{{ version }}.tar.gz
  sha256: ec051cb568324de878828fae96379b71858933413e185148acb6c162851ab23c

build:
  number: 0
  # skip s390x: no libgdal
  skip: true  # [py<39 or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=0.29
    # https://github.com/geopandas/pyogrio/blob/v0.10.0/setup.py#L24
    - libgdal >=2.4.0
    # https://github.com/geopandas/pyogrio/blob/v0.10.0/pyproject.toml#L5
    - versioneer ==0.28
    - tomli 2.0.1  # [py<311]
  run:
    - python
    - libgdal
    # https://github.com/geopandas/pyogrio/blob/v0.10.0/pyproject.toml#L31
    - certifi
    - packaging
    - numpy

test:
  imports:
    - pyogrio
  requires:
    - pip
    - pytest
  source_files:
    - pyogrio/tests
  commands:
    - pip check
    # Check that pip gets the correct version 
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Skip tests that require a network connection
    # and tests that require the Arrow write API
    # https://github.com/geopandas/pyogrio/blob/v0.10.0/setup.cfg#L5-L6
    - pytest -vv -m "not (network or requires_arrow_write_api)" pyogrio/tests

about:
  home: https://github.com/geopandas/pyogrio/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Vectorized vector I/O using GDAL
  description: |
    Provide faster I/O using GDAL OGR to read / write vector geospatial files.
    Intended for use with libraries that consume WKB for their internal
    constructs, such as pygeos.
  doc_url: https://pyogrio.readthedocs.io/
  dev_url: https://github.com/geopandas/pyogrio

extra:
  recipe-maintainers:
    - brendan-ward
    - jorisvandenbossche
    - martinfleis
